apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitcoind.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  rpcpassword: {{ (.Values.configuration.rpcpassword | default (randAlphaNum (int .Values.configuration.passwordLength))) | b64enc }}
  rpcuser: {{ (.Values.configuration.rpcuser | default (randAlphaNum 8)) | b64enc }}
