apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitcoind.name" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Release.IsInstall }}
  rpcpassword: {{ .Values.configuration.rpcpassword | default (randAlphaNum (int .Values.configuration.passwordLength)) | b64enc }}
  {{ else }}
  rpcpassword: {{ index (lookup "v1" "Secret" .Release.Namespace "bitcoind").data "rpcpassword" | default (.Values.configuration.rpcpassword | b64enc) }}
  {{ end }}
  {{- if .Release.IsInstall }}
  rpcuser: {{ .Values.configuration.rpcuser | default (randAlphaNum 8) | b64enc }}
  {{ else }}
  rpcuser: {{ index (lookup "v1" "Secret" .Release.Namespace "bitcoind").data "rpcuser" | default (.Values.configuration.rpcuser | b64enc) }}
  {{ end }}
