bitcoind:
  namespace: bitcoind
  image:
    repository: bitcoin/bitcoin
    tag: 28
    digest: sha256:40c4d17f6cf0b560a61d33a1d97ccb8b6d407db29e614d2c598cb9b2483a4383
    pullPolicy: IfNotPresent
  configuration:
    printtoconsole: 1
    signet: 1 
    server: 1 
    rpcallowip: 0.0.0.0/0
    rpcbind: "0.0.0.0" 
    rpcport: "38332"
    disablewallet: 1 
    prune: 12000 
    rpcuser: "foo"
    rpcpassword: "bar"
    passwordLength: 50 

bitcoin-exporter:
  namespace: bitcoind
  image:
    repository: chakrellah/bitcoin-exporter
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9100
  config:
    rpcURL: "http://bitcoind:38332"
    metricsPort: 9100
  secret:
    rpcuser: "foo"
    rpcpassword: "bar"
  ingress:
    host: btc-exporter.local

prometheus:
  forceNamespace: monitoring
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    service:
      type: ClusterIP
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 800Mi
        cpu: 400m
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - "prometheus.local"
      path: /
      pathType: Prefix
  extraScrapeConfigs: |
    - job_name: 'btc-exporter'
      scrape_interval: 10s
      static_configs:
        - targets: ['bitcoin-stack-bitcoin-exporter.bitcoind.svc.cluster.local:9100']
  
  #The following subcharts are disabled from the prometheus chart to be managed properly under the umbrella chart.
  kube-state-metrics:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    enabled: false

## kube-state-metrics sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
##
kube-state-metrics:
  enabled: true
  namespaceOverride: monitoring
## prometheus-node-exporter sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter
##
prometheus-node-exporter:
  enabled: true
  namespaceOverride: monitoring
  rbac:
    pspEnabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false
## prometheus-pushgateway sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway
##
prometheus-pushgateway:
  enabled: true
  namespaceOverride: monitoring
  serviceAnnotations:
    prometheus.io/probe: pushgateway

grafana:
  namespaceOverride: monitoring
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://bitcoin-stack-prometheus-server:80
          isDefault: true
  dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: true
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      btc-dashboard:
        url: https://gist.githubusercontent.com/Aminechakr/daae256f64bf21eb8f10998ffd3ac7a5/raw/eb0655db43ef82cce7a14a793d7da67d6aa91ba2/btc_exporter.json
        datasource: Prometheus
      kubernetes-resources:
        gnetId: 6417 
        revision: 1
        datasource: Prometheus
  rbac:
    pspEnabled: false
  podSecurityPolicy:
    enabled: false
  testFramework:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    hosts:
      - "grafana.local"
    path: /
    pathType: Prefix

