apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-exporter-config
  namespace: {{ .Values.namespace }}
data:
  rpc_url: {{ .Values.config.rpcURL | quote }}
  metrics_port: {{ .Values.config.metricsPort | quote }}
