apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "bitcoin-exporter.fullname" . }}
  labels:
    app: {{ include "bitcoin-exporter.name" . }}
    chart: {{ include "bitcoin-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bitcoin-exporter.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bitcoin-exporter.name" . }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "bitcoin-stack"
        vault.hashicorp.com/agent-inject-secret-bitcoin: "secret/data/bitcoin-stack"
        vault.hashicorp.com/agent-inject-template-bitcoin: |
          {{`{{- with secret "secret/data/bitcoin-stack" -}}
          export RPC_USER="{{ .Data.data.rpcuser }}"
          export RPC_PASSWORD="{{ .Data.data.rpcpassword }}"
          {{- end -}}`}}
    spec:
      serviceAccountName: vault-auth-bitcoin
      containers:
        - name: bitcoin-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              source /vault/secrets/bitcoin
              ./bitcoin-exporter
          env:
            - name: RPC_URL
              value: {{ .Values.config.rpcURL | quote }}
            - name: METRICS_PORT
              value: {{ .Values.config.metricsPort | quote }}
          ports:
            - containerPort: {{ .Values.config.metricsPort }}
