apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bitcoin-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bitcoin-exporter.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
