apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-exporter-secret
  labels:
    app: {{ include "bitcoin-exporter.name" . }}
    chart: {{ include "bitcoin-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  rpcuser: {{ index (lookup "v1" "Secret" .Release.Namespace "bitcoind").data "rpcuser" }}
  rpcpassword: {{ index (lookup "v1" "Secret" .Release.Namespace "bitcoind").data "rpcpassword" }}