apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-exporter-secret
type: Opaque
data:
  rpcUser: {{ .Values.secret.rpcUser | b64enc | quote }}
  rpcPassword: {{ .Values.secret.rpcPassword | b64enc | quote }}
