apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "bitcoin-exporter.fullname" . }}
  labels:
    app: {{ include "bitcoin-exporter.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.metricsPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "bitcoin-exporter.name" . }}
