apiVersion: v2
appVersion: "1.0"
description: A Helm chart for the Bitcoin Exporter service
keywords:
- bitcoin
- metrics
- prometheus
- helm
maintainers:
- email: chakrelllah@gmail.com
  name: Amine Chakrellah
name: bitcoin-exporter
sources:
- https://github.com/aminechakr/bitcoin-node-observer
version: 0.1.0
