name: Helm Chart - Bitcoin Node

on:
  push:
    paths:
      - 'bitcoind/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'bitcoind/**'
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1

    - name: Run chart-testing (lint)
      run: ct lint --target-branch main --charts ./bitcoind

    - name: Create kind cluster
      uses: helm/kind-action@v1.8.0

    - name: Set KUBECONFIG for KinD
      run: echo "KUBECONFIG=${HOME}/.kube/config" >> $GITHUB_ENV

    - name: Run chart-testing (install)
      run: ct install --target-branch main --charts ./bitcoind

  release:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Package Helm Chart
      run: helm package ./bitcoind --destination ./charts

    - name: Deploy Helm Chart to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./charts
